FROM tiangolo/uvicorn-gunicorn:python3.10

LABEL maintainer="OpenQDA Project <openqda@uni-bremen.de>"

RUN apt install --no-install-recommends -y pandoc
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt
COPY ./app /app
COPY ./.env /app

EXPOSE 9444
