name: Backend Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # this is not a good solution but we currently
      # don't know where these files come from,
      # seems like an issue with the detached HEAD
      - name: Cleanup
        run: |
          rm web/app/Console/Commands/SendSystemEmail.php
          rm web/app/Mail/SystemMessage.php

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer global require laravel/pint:1.21.0

      - name: Run Pint
        run: pint --test
